### ISSUE TITLE
Norwegian language files

### ISSUE THREAD

**Issue by HRN65** [magicsunday/webtrees-descendants-chart#1]
Thank you for another great addon. Here are the two norwegian language files nb and nn
[lang.zip](https://github.com/magicsunday/webtrees-descendants-chart/files/6152226/lang.zip)

**Comment by hahalj** [comment]
Thank you for this fantastic addon! I've translated it to Swedish, if you'd like to include that in your project.
Thanks.
[sv.zip](https://github.com/magicsunday/webtrees-descendants-chart/files/6332261/sv.zip)

**Comment by magicsunday** [comment]
I committed it. Thanks, but please open a new/separate issue next time.
