### ISSUE TITLE
Text can overflow box

### ISSUE THREAD

**Issue by ddrury** [magicsunday/webtrees-descendants-chart#12]
As per title, particularly noticeable with dates of the format "between January 1849 and March 1849".

Could possibly shorten text to "Bet Jan and Mar 1849"

**Comment by ddrury** [comment]
Hi,

Here's a suggestion that shortens the text but keeps the international format:

In `IndividualTrait::getIndividualData()`

Add line `$date_format = Str_replace(['%l', '%F'], ['%D', '%M'], I18N::dateFormat());`
change birth (& death) date lines to
` 'birth'            => strip_tags($individual->getBirthDate()->display(false, $date_format)),`

(also works for pedigree chart)

![before](https://user-images.githubusercontent.com/104515/131330078-f8f5156f-6538-49f7-a50c-ab413d4f5e56.jpg) ![after](https://user-images.githubusercontent.com/104515/131330122-95aeaeb9-cded-4703-87bf-38183b7b81af.jpg)

**Comment by reteP-riS** [comment]
Just tested this. The proposed change shortens the date format, but is still way too long in case you have days in there as well, e. g. "between 23 Jul 1909 and 23 Sep 1909".

**Comment by ddrury** [comment]
Yeah,
I realised the change above wouldn't be a complete solution. It's simple to change the standard php date formatting characters. The trouble is the Gedcom modifiers (after, between, before, etc.) are difficult to intercept **before** they are internationalised.

See https://github.com/fisharebest/webtrees/issues/4046

**Comment by magicsunday** [comment]
This change cuts off dates that are too long to prevent them from overflowing the edge of the box. Unfortunately, this doesn't work for multibyte languages like hebrew yet. 

The complete date is still available as additional <title> attribute.
