### ISSUE TITLE
Box of individual with unknown sex is missing dashed border

### ISSUE THREAD

**Issue by reteP-riS** [magicsunday/webtrees-descendants-chart#16]
Unlike the pedigree chart the descendants chart does NOT display the dashed border for an individual with unknown sex.

**Comment by reteP-riS** [comment]
Using release 1.0.2, but I don't see this change https://github.com/magicsunday/webtrees-descendants-chart/commit/c78d4b49f8125c518a9c86c4e9e27c4ca447b202 neither in release 1.0.1 nor in 1.0.2.

**Comment by reteP-riS** [comment]
My bad. I was in fact NOT using relase 1.0.2, but 1.0.1. Don't know what happened, but now with release 1.0.2 everything works as expected.

**Comment by magicsunday** [comment]
😄
