### ISSUE TITLE
1.03-dev keeps loading, showing no data.

### ISSUE THREAD

**Issue by MiloBeenhakker** [magicsunday/webtrees-descendants-chart#17]
Hello, I'm using all your modules for my family tree website, a great replacement for the originals!
Today I installed webtrees-descendants-chart-1.03-dev and I have to report the following: after clicking descendants-chart in the menu there is no data showing, it keeps looping in the loading stage. There's no error reports generated in the web logs. If any additional information is needed, please let me know.

![Schermafbeelding 2021-10-02 134431](https://user-images.githubusercontent.com/77068125/135715264-2ea0874d-a590-4715-9a95-e4ec40be9e9d.jpg)

**Comment by magicsunday** [comment]
Hi. What version of webtrees and PHP do you use? 

The *main* branch requires PHP 7.4 and is only compatible with latest *main* branch of webtrees.

**Comment by MiloBeenhakker** [comment]
Hi.
Thanks for the quick reply, Webtrees version 2.0.16 & PHP Version 7.4.16

The previous version 1.02 was working perfect

**Comment by MiloBeenhakker** [comment]
Maybe slightly offtopic for this threat because it matters different modules.

I also updated  webtrees-pedigree-chart-1.2.6-dev > webtrees-pedigree-chart-1.2.7-dev and the behaviour is similar to updating webtrees-descendants-chart-1.02-dev > webtrees-descendants-chart-1.03-dev. No data will show and it hangs in the loading process.

The update from webtrees-fan-chart-2.2.0 > webtrees-fan-chart-2.2.2-dev works flawless!

**Comment by magicsunday** [comment]
Same Problem for pedigree Chart. Please use latest release version if you are using webtrees 2.0.16. 

There are some changes in current Main Branch of webtrees which are only compatible with latest main/master branch of the modules.

**Comment by MiloBeenhakker** [comment]
The control panel says I'm using the latest version of webtrees which is 2.0.16, and there's no notification of a new version.  
Also on the webtrees download page 2.0.16 is the latest version, am I missing something?

**Comment by magicsunday** [comment]
If you are using the release version of webtrees (https://github.com/fisharebest/webtrees/releases) you als should use the release version of the modules (https://github.com/magicsunday/webtrees-descendants-chart/releases, ...). The development branches may not be compatible with the release version. The current dev-branches of the modules contains mostly changes, regarding changes in the webtrees-sources. If a new version of webtrees is released a new version of the modules will be release afterwards.

**Comment by MiloBeenhakker** [comment]
Ok clear, thanks for your clear explanation. 
The reason I updated the modules was because I recieved  messages in the Webtrees control panel that updates were available.
Although it says clearly in the module titles it matters dev version, I wasn't aware of this.
I will roll back to  the release version of the modules.
