### ISSUE TITLE
Update: wt 2.1.1 and chart V1.1.0 -> rotating circle

### ISSUE THREAD

**Issue by ungeahnt** [magicsunday/webtrees-descendants-chart#25]
I've updated wt from 2.0.23 to 2.1.1 and also the addon to the latest release ([V1.1.0](https://github.com/magicsunday/webtrees-descendants-chart/releases/tag/1.1.0)) 

But when I open the chart I see only a rotating circle.

In #23 you write "Try the 2.1 branch.". Do I use the correct release/Version?
I've also tested with php7.4 and 8.0. Without success.

**Comment by magicsunday** [comment]
Sorry I didn‘t find the time to create a release by now. Please try the branch https://github.com/magicsunday/webtrees-descendants-chart/tree/2.1

**Comment by ungeahnt** [comment]
Thanks a lot! It's working again.
