### ISSUE TITLE
Show the second name of individual in the second language

### ISSUE THREAD

**Issue by zhoueysun** [magicsunday/webtrees-descendants-chart#28]
I would like to have the second name, if it's in another language as the primary name, displayed, similar to what fisharebest has in his default descendent chart.
![descendents](https://user-images.githubusercontent.com/14076780/173173261-30b4ff9c-1ead-4001-84e2-ca7e8bb2e972.jpg)
Your Fan Chart has inconsistently the second name displayed:
![fan chart](https://user-images.githubusercontent.com/14076780/173173321-29cc1b03-d97b-442b-bf59-040bcdcb7fb1.png)

**Comment by magicsunday** [comment]
Could you please provide me an example gedcom file?

**Comment by zhoueysun** [comment]
[Use](url) Joe Min as your default person. I checked this and it should work. Thank you for your attention and the wonderful work.
[clippings-2022-06-11.zip]
The line feed is CR/LF (windows). If you want me to re-export the GED as line feed: LF (unix), LMK

removed gedcom for privacy reasons

**Comment by arbor95** [comment]
in gedcom there is no second name.
sometimes you are using NAME with a 
2 TYPE pinyin
or / and
2 TYPE simplified
What would be the second?
(on the other hand you do not need to have an entry without TYPE)

**Comment by zhoueysun** [comment]
@arbor95 said: _in gedcom there is no second name._ 
I am unsure how to comment. Maybe I should clarify by stating that I am reordering the 1 NAME tag.
Early in my genealogical studies I assumed everyone had a single name and there was a universal standard way to romanize it. Hence some of my entries in the clippings gedcom have the Chinese name and the romanized name. However, in Chinese genealogy, mainly males had multiple given names. A popular example is Sun Yat-sen (see: https://en.wikipedia.org/wiki/Sun_Yat-sen ). Even though currently in the Peoples Republic of China there is one way to romanize names (pinyin), prior decades there were other ways to romanized Chinese characters. The different dialects had different pronunciation. You recognize the Cantonese and Mandarin dialect as an example. The use of the TYPE tag is important to distinguish what category each name is. The power of webtrees is the ability to enter all these different names into the database.
@fisharebest was able to have his descendants charting recognize the difference between the romanized spelling and the Asian characters. 
So I use the webtrees EDIT function to reorder the names, hopefully making it easier for @magicsunday to  know what name to use in the limited space in the descendant chart.
@magicsunday here is a gedcom of inlaws who have romanized and Korean, and Chinese names. I have reordered the names in the gedcom so the Korean is the 1st or second non Latin name. The Chinese name is the 3rd name in the gedcom.
I hope this helps.
[korean-chinese.zip](https://github.com/magicsunday/webtrees-descendants-chart/files/8892747/korean-chinese.zip)

**Comment by zhoueysun** [comment]
> Could you please provide me an example gedcom file?

Would it help if I share a GEDCOM with profile pictures in addition to the second language?

**Comment by fisharebest** [comment]
The chart draws names circumferentially for the first 4 generations.  These appear to include the alternate name - `GedcomRecord::alternateName()`.

The chart draws names radially for the last 2 generations.  It does not display the alternate name here - presumably because there is insufficient space...

**Comment by magicsunday** [comment]
Thats rights, there is not enough space to draw the alternate names everywhere.

**Comment by magicsunday** [comment]
Fixed with https://github.com/magicsunday/webtrees-descendants-chart/commit/3c0eb3c48e2cddd066bec7c6497291fb622cb052

**Comment by magicsunday** [comment]
Should be fixed with https://github.com/magicsunday/webtrees-descendants-chart/releases/tag/1.7.0
