### ISSUE TITLE
Error en webtrees-descentes-chart en webtrees 2.1.15

### ISSUE THREAD

**Issue by BernatBanyuls** [magicsunday/webtrees-descendants-chart#30]
Webtrees-descendents-chart me produce el siguiente error en webtrees 2.1.15

Alguna ayuda?
Gracias.

View file not found: …/modules_v4/webtrees-descendants-chart/src/../resources/views/modules/descendants-chart/chart.phtml …/app/View.php:260
#0 …/app/View.php(183): Fisharebest\Webtrees\View->getFilenameForView()
#1 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#2 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#3 …/app/Http/ViewResponseTrait.php(50): view()
#4 …/modules_v4/webtrees-descendants-chart/src/Module.php(176): Fisharebest\Webtrees\Module\AbstractModule->viewResponse()
#5 …/app/Http/Middleware/RequestHandler.php(55): MagicSunday\Webtrees\DescendantsChart\Module->handle()
#6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#7 …/modules_v4/reminder/src/Modules/ReminderModule.php(97): Middleland\Dispatcher->handle()
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Reminder\Modules\ReminderModule->process()
#9 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(277): Middleland\Dispatcher->handle()
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process()
#11 …/modules_v4/faces/src/Modules/FacesModule.php(94): Middleland\Dispatcher->handle()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process()

**Comment by magicsunday** [comment]
Please use the provided issue templates to report bugs otherwise its hard to know what you have done. I do not see any errors in my test environment. Please provide more information.

**Comment by magicsunday** [comment]
Same as https://github.com/magicsunday/webtrees-pedigree-chart/issues/53
