### ISSUE TITLE
Fatal webtrees error when install descendants chart

### ISSUE THREAD

**Issue by krmcelhinney** [magicsunday/webtrees-descendants-chart#36]
I have installed the fan chart, pedigree chart and descendants charts. The fan chart and pedigree chart work fine. But, when I install the descendants chart I get a fatal error for webtrees, and I have to delete the module before webtrees works again.

The error I get is - 
Fatal error in module: webtrees-descendants-chart
Error: Call to undefined method Fisharebest\Webtrees\Registry::container() in /home/mcelhinn/public_html/family/modules_v4/webtrees-descendants-chart/module.php:25 Stack trace: #0 /home/mcelhinn/public_html/family/app/Services/ModuleService.php(735): include() #1 /home/mcelhinn/public_html/family/app/Services/ModuleService.php(709): Fisharebest\Webtrees\Services\ModuleService::load() #2 [internal function]: Fisharebest\Webtrees\Services\ModuleService::Fisharebest\Webtrees\Services\{closure}() #3 /home/mcelhinn/public_html/family/vendor/illuminate/collections/Collection.php(695): array_map() #4 /home/mcelhinn/public_html/family/app/Services/ModuleService.php(718): Illuminate\Support\Collection->map() #5 /home/mcelhinn/public_html/family/app/Services/ModuleService.php(630): Fisharebest\Webtrees\Services\ModuleService->customModules() #6 /home/mcelhinn/public_html/family/app/Cache.php(60): Fisharebest\Webtrees\Services\ModuleService->Fisharebest\Webtrees\Services\{closure}() #7 /home/mcelhinn/public_html/family/vendor/symfony/cache/Adapter/ArrayAdapter.php(84): Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}() #8 /home/mcelhinn/public_html/family/app/Cache.php(61): Symfony\Component\Cache\Adapter\ArrayAdapter->get() #9 /home/mcelhinn/public_html/family/app/Services/ModuleService.php(663): Fisharebest\Webtrees\Cache->remember() #10 /home/mcelhinn/public_html/family/app/Services/ModuleService.php(581): Fisharebest\Webtrees\Services\ModuleService->all() #11 /home/mcelhinn/public_html/family/app/Http/Middleware/UseLanguage.php(84): Fisharebest\Webtrees\Services\ModuleService->findByInterface() #12 /home/mcelhinn/public_html/family/app/Http/Middleware/UseLanguage.php(63): Fisharebest\Webtrees\Http\Middleware\UseLanguage->languages() #13 /home/mcelhinn/public_html/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process() #14 /home/mcelhinn/public_html/family/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle() #15 /home/mcelhinn/public_html/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process() #16 /home/mcelhinn/public_html/family/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle() #17 /home/mcelhinn/public_html/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process() #18 /home/mcelhinn/public_html/family/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle() #19 /home/mcelhinn/public_html/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process() #20 /home/mcelhinn/public_html/family/app/Http/Middleware/BadBotBlocker.php(287): Middleland\Dispatcher->handle() #21 /home/mcelhinn/public_html/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process() #22 /home/mcelhinn/public_html/family/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle() #23 /home/mcelhinn/public_html/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process() #24 /home/mcelhinn/public_html/family/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle() #25 /home/mcelhinn/public_html/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process() #26 /home/mcelhinn/public_html/family/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle() #27 /home/mcelhinn/public_html/family/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process() #28 /home/mcelhinn/public_html/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process() #29 /home/mcelhinn/public_html/family/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle() #30 /home/mcelhinn/public_html/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process() #31 /home/mcelhinn/public_html/family/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle() #32 /home/mcelhinn/public_html/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process() #33 /home/mcelhinn/public_html/family/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle() #34 /home/mcelhinn/public_html/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process() #35 /home/mcelhinn/public_html/family/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle() #36 /home/mcelhinn/public_html/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process() #37 /home/mcelhinn/public_html/family/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle() #38 /home/mcelhinn/public_html/family/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process() #39 /home/mcelhinn/public_html/family/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #40 /home/mcelhinn/public_html/family/app/Webtrees.php(275): Middleland\Dispatcher->dispatch() #41 /home/mcelhinn/public_html/family/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch() #42 /home/mcelhinn/public_html/family/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest() #43 {main}

**Comment by magicsunday** [comment]
Hi, could you please stick to the bug report template and fill out all necessary information? Otherwise I only could guess whats going wrong. 

https://github.com/magicsunday/webtrees-descendants-chart/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=
