### ISSUE TITLE
Families

### ISSUE THREAD

**Issue by 06Games** [magicsunday/webtrees-descendants-chart#4]
The fact that the spouse is not displayed poses a problem when the individual has had children with different people (in the case of a re-marriage for example)
Thus, I think that for the sake of consistency, it would be useful to add the spouses and distribute the children according to the families.   
  
  
As displayed by the module:
![image](https://user-images.githubusercontent.com/24252743/111493558-f51ceb00-873d-11eb-8ae5-26afa16a8fcd.png)

In reality:
![image](https://user-images.githubusercontent.com/24252743/111493833-37dec300-873e-11eb-949d-4547322dd4ae.png)

**Comment by magicsunday** [comment]
What would you suggest how this could be best presented?

**Comment by 06Games** [comment]
A bit like what MyHeritage does:
![image](https://user-images.githubusercontent.com/24252743/114310931-ea5f3700-9aec-11eb-8e2b-e05338bfd27c.png)

Also, it is possible to do it the Geneanet way (the children are not linked in the same way)
![image](https://user-images.githubusercontent.com/24252743/114311023-4f1a9180-9aed-11eb-823e-4a9415dc13ca.png)

**Comment by sachinwadhwa** [comment]
I second that - missing spouse really a major drawback..

**Comment by ThomasT02** [comment]
For example here you can see a graphic with two or more marriages.
What you cannot see ist the first marriage of women and their children, when men and women are marrying the second time. (His children, her children and common children in one family)

![grafik](https://user-images.githubusercontent.com/46403012/147850472-4fda64b6-58f3-48dd-8246-b3597263d512.png)

**Comment by enes73** [comment]
> What would you suggest how this could be best presented?

Here is my example... :)

![Example](https://user-images.githubusercontent.com/6985394/215057380-0fa04285-d7de-440c-939c-61af31c91598.jpg)

I hope that you'll add this feature soon.

Thanks in advance

**Comment by magicsunday** [comment]
Please see #8 


![](https://user-images.githubusercontent.com/564393/221640225-22f413c9-e0dc-4f8c-a8e0-e5e2d99e258d.png)

**Comment by enes73** [comment]
Thanks for adding spouses, but I think that this view is not logical. Spouses are vertical and children horisontal, and not man-wife par not visually connected well. If you can do like this https://github.com/magicsunday/webtrees-descendants-chart/issues/4#issuecomment-1406269032 it's been awesome :)

If you cannot do like that, maybe you can make 3x man-wife par and his children:

MAN-WIFE#1 ---------- MAN-WIFE#2 ----------MAN-WIFE#3
∙∙∙∙∙∙∙∙∙∙∙∙∙∙ ↓  ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙ ↓ ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙ ↓
(below his children's)    (below his children's)     (below his children's)

Again, THANK YOU for your work for this AWESOME plugin...

**Comment by magicsunday** [comment]
I don't get the point. For me it looks like #4

![grafik](https://user-images.githubusercontent.com/564393/221829297-879d4afd-962f-406c-ac0e-8dae3cba4189.png)

**Comment by enes73** [comment]
If look like this picture it's GREAT! I react on your picture from this post https://github.com/magicsunday/webtrees-descendants-chart/issues/4#issuecomment-1446757832

Thank again for your great work!!!
