### ISSUE TITLE
Displaying spouses

### ISSUE THREAD

**Issue by HRN65** [magicsunday/webtrees-descendants-chart#40]
Could we please have spouses hidden by default? And maybe also the option to not display "Show more options"? 
I guess because of pedegree collapse and lines crossing several times in my family tree, the descendants chart looks cluttered when spouses are not hidden.

![2108231654](https://github.com/magicsunday/webtrees-descendants-chart/assets/55854079/e6ce93c5-0637-4c57-8adc-680c997cb692)

**Comment by magicsunday** [comment]
Uh, that looks very strange indeed. Would it be possible if you could please provide me with a GEDCOM example that recreates this tattered layout? Maybe that could be fixed somehow.

**Comment by hartenthaler** [comment]
For me, it works as a charm, besides one minor point: would it be possible to put the crossing lines into the background?
![descendants-chart (2)](https://github.com/magicsunday/webtrees-descendants-chart/assets/6324175/347ac6ca-d6d8-4b33-a50d-b8e9f84089f7)

**Comment by HRN65** [comment]
Thank you for looking into this! I tested some gedcom files available online, and found this family tree of Charles II of Spain, known for pedegree collapse. The Uncorrected CoR (Coefficient of Relationship) between his parents is 37.01% trough 18 relationships.
Try displaying descendants of Maria Anna of Bavaria
https://[paginas.fe.up.pt/~jlborges/visualgenealogy/charles_II_of_spain.ged](https://paginas.fe.up.pt/~jlborges/visualgenealogy/charles_II_of_spain.ged)

![2208231624](https://github.com/magicsunday/webtrees-descendants-chart/assets/55854079/1a29bba2-3400-464f-8401-69ac3bac4918)

**Comment by magicsunday** [comment]
Hi, I found some glitches I could fix. I think it looks fine now.

![grafik](https://github.com/magicsunday/webtrees-descendants-chart/assets/564393/7ef696a2-4647-4127-ae23-ff209f6a4273)

**Comment by magicsunday** [comment]
Fixed in https://github.com/magicsunday/webtrees-descendants-chart/releases/tag/1.5.0

**Comment by HRN65** [comment]
Thank you, that was quick! The 1.5.1 works like a charm!
