### ISSUE TITLE
Option to show spouses does not work anymore in 1.5.0

### ISSUE THREAD

**Issue by hartenthaler** [magicsunday/webtrees-descendants-chart#41]
If I select to show the spouses nothing is shown (empty diagram). If I hide the spouses it is working as expected.

**Comment by magicsunday** [comment]
I have notices this. I did some mistakes during merging.

**Comment by zeezhao** [comment]
Hi. Same issue here. Please see my other comments on v1.5.0 here:
https://github.com/magicsunday/webtrees-descendants-chart/issues/39#issuecomment-1689998739

Not sure how to reopen #39 . Thanks

**Comment by magicsunday** [comment]
Please recheck with https://github.com/magicsunday/webtrees-descendants-chart/releases/tag/1.5.1

**Comment by hartenthaler** [comment]
Now it works perfect for me. Thank you for this impressive module!
