### ISSUE TITLE
When birthdate for at least one child not set at a level, please preserve original webtrees order.

### ISSUE THREAD

**Issue by zeezhao** [magicsunday/webtrees-descendants-chart#43]
**Describe the bug**
When birthdates not set, children at a particular level/tree appear to be sorted randomly.

**To Reproduce**
In a branch where at least one child does not have birthdate set, order of children is random instead of original webtrees order.

**Expected behavior**
When birthdate for at least one child not set at a level, please preserve original webtrees order.

**Comment by magicsunday** [comment]
Have you tried version 1.5.1? If so, could you please provide me with a GEDCOM example so that I can understand the problem more easily?

**Comment by zeezhao** [comment]
Yes I have tried v1.5.1. It is the same issue as in previous versions 1.4.1, 1.4.2, 1.5.0.

Unfortunately, I can not provide the GEDCOM file as it is has over 500 individuals and I will have to get permission to export it.

But using my example from #39, when all the children C1, C2, C3, C4 have birthdate set, the sorting by date works as expected.

But :
- if at least one of the children is not set,  OR
- when the birthdate is hidden due to privacy via "Control panel/Manage family trees/Privacy" menu  then "Privacy restrictions" section, I have an entry "<html><body>


All records | Birth | Hide from everyone
-- | -- | --


</body>
</html>
- then the children appear random instead of the fixed webtree order.

edit:
In this scenario, they appear to be ordered by death date , when this should not be a factor at all.

**Comment by magicsunday** [comment]
Could you please check, if https://github.com/magicsunday/webtrees-descendants-chart/commit/e88728625d3a9e6fa3c74fbef26e2e25fbcae66b fixes your problem?

**Comment by zeezhao** [comment]
Thank you - this seems to work! I will do more testing to confirm.

**Comment by zeezhao** [comment]
This looks fine now. Thank you for your swift response and hard work!
