### ISSUE TITLE
New browser tap created when selecting (clicking on) the root person (and spouse) of the chart

### ISSUE THREAD

**Issue by gudjonsi** [magicsunday/webtrees-descendants-chart#47]
**Describe the bug**
New browser tap always created when selecting (clicking on) the root person (or his/her spouse) of the chart.

**To Reproduce**
1. Go to 'Select an individual'
2. Click on 'Menu > Chart > Descendants chart'
3. Scroll down to 'Click on (select/open) the root individual (or his/her spouse) in the chart to open the peron in the wt individual page'
4. Error 'A new browser tab is always opened displaying the selected person on the wt individual page instead of opening it in the same browser tap'

**Expected behavior**
Previous version of the Descendants Chart Module always opened the root person (or spouse) in the same browser tap.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - Browser [e.g. firefox, safari]
 - Webtrees version [e.g. 2.1.17]
 - Version of descendants chart [e.g. 1.6.0]

**Additional context**
Was using the Descendants Chart Module version 1.4.0 without this problem.

**Comment by magicsunday** [comment]
Hi, this is not a bug, this is a feature. You remain in the chart itself and can still look at the details of a person without having to reload the chart afterwards.

**Comment by gudjonsi** [comment]
Ok, thanks. Would it possible to disable this particular feature by using a specific code <style> ???? </style> in the CSS & JS Module for webtrees?
