### ISSUE TITLE
Start with all Presentation options checked

### ISSUE THREAD

**Issue by arbor95** [magicsunday/webtrees-descendants-chart#52]
**Is your feature request related to a problem? Please describe.**
The display looks better.

**Describe the solution you'd like**
The display looks better.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by magicsunday** [comment]
Next time please provide a little more information regarding the problem/change request. You are also welcome to write this in German if it is difficult to explain in English.

I have added a configuration panel so that you can specify the initial settings for the chart.
