### ISSUE TITLE
Help / Hint for usage

### ISSUE THREAD

**Issue by arbor95** [magicsunday/webtrees-descendants-chart#53]
**Is your feature request related to a problem? Please describe.**
The usage of right mouse button is not a usual click, that a user does.
The centering to a clicked individuums is a bit surprising. (and how to go back)

**Describe the solution you'd like**
I would like a help button.

**Describe alternatives you've considered**
the mouse over, if the right mouse button has not been clicked, could show: "use right mouse button" instead of name (already shown on individuum)

**Additional context**
If a screenshot will be necessary: tell me.

**Comment by magicsunday** [comment]
I can't really understand your problem. There is no right click in the descendant diagram.

**Comment by arbor95** [comment]
Sorry, should have been there: https://github.com/magicsunday/webtrees-fan-chart/issues/83
