### ISSUE TITLE
Inverted order of Chinese names

### ISSUE THREAD

**Issue by iyoua** [magicsunday/webtrees-descendants-chart#55]
After upgrading the module version from 1.6.1 to 1.8.0, the display order of Chinese names has been reversed. The upgraded display order does not comply with the Chinese name rules. But when switching the language to English, its Chinese name rules are correct. How to solve this problem?

**Comment by iyoua** [comment]
![chinese1 6 1](https://github.com/magicsunday/webtrees-descendants-chart/assets/102014216/e18f95fe-224b-478a-975c-a306ad2bc14d)
![chinese1 8 0](https://github.com/magicsunday/webtrees-descendants-chart/assets/102014216/8643ac38-8a75-43ea-bda0-e88c20d013b2)
![english1 8 0](https://github.com/magicsunday/webtrees-descendants-chart/assets/102014216/3f10d1e9-5d59-4d41-9f38-b1ebb6124cfd)

**Comment by magicsunday** [comment]
Same problem as https://github.com/magicsunday/webtrees-pedigree-chart/issues/67

**Comment by magicsunday** [comment]
@iyoua 

Could you please test with latest version from branch "2.1" if https://github.com/magicsunday/webtrees-descendants-chart/commit/660012796c1dfa85488bc75a26fcf46c77b9a3e2 fixes your issue?

**Comment by iyoua** [comment]
The order of Chinese names is now displayed normally. Thank you!
