### ISSUE TITLE
Descendants chart not listed on chart module

### ISSUE THREAD

**Issue by abdullahaaf** [magicsunday/webtrees-descendants-chart#59]
**Describe the bug**
Installed on webtrees `2.1.20` either using `composer`  or manually, but module not listed on charts

**To Reproduce**
1. Go to Control Pane
2. Click on Charts
3. Scroll down to List of Charts
4. Descendants Chart not listed

**Expected behavior**
As mentioned on docs, after install module should listed on `Charts` module

**Screenshots**
<img width="657" alt="image" src="https://github.com/magicsunday/webtrees-descendants-chart/assets/16618535/1ef00f65-3975-4f95-85bf-eac41234ac66">
<br>
<img width="180" alt="image" src="https://github.com/magicsunday/webtrees-descendants-chart/assets/16618535/e6b765e4-4c96-48de-a711-d1a6947a66b8">

**Desktop (please complete the following information):**
 - Browser edge
 - Webtrees 2.1.20
 - Version of descendants chart 1.8.0

**Comment by magicsunday** [comment]
Hm. I can't reproduce your problem. If I install the module using composer, everything is fine:

```
(tags/2.1.20^0) XYZ@PRIVATE:/sharedfolders/web/webtrees-2.0# composer require magicsunday/webtrees-descendants-chart --update-no-dev
...
./composer.json has been updated
Running composer update magicsunday/webtrees-descendants-chart
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking magicsunday/webtrees-descendants-chart (1.8.1)
  - Locking magicsunday/webtrees-module-installer-plugin (1.3.2)
Writing lock file
Installing dependencies from lock file
...
```

Afterward the module and its files resides in /sharedfolders/web/webtrees-2.0/modules_v4/webtrees-descendants-chart

**Comment by magicsunday** [comment]
Did it work with modules other than mine?

**Comment by abdullahaaf** [comment]
not yet tested with other module. 
This is first time I'm using webtrees.

Have you tested with webtrees version similar to mine?

**Comment by magicsunday** [comment]
Yes. I'm always using the latest version of webtrees.

**Comment by abdullahaaf** [comment]
after put module on `modules/v4` directory, do we need some actions or this module automatically listed on webtress chart module?

**Comment by magicsunday** [comment]
Please try first with some other module (other author) to be sure the problem is related to this module. If Problem persists it may be problem of webtrees itself.

**Comment by reteP-riS** [comment]
I suspect you downloaded the latest code instead of the latest release from https://github.com/magicsunday/webtrees-descendants-chart/releases/tag/1.8.1.
If you unzip this release into modules_v4 then there is no need to rename anything.

**Comment by abdullahaaf** [comment]
<img width="446" alt="image" src="https://github.com/magicsunday/webtrees-descendants-chart/assets/16618535/400c81da-7523-4c2e-a252-8a04ceeb9a31">

@reteP-riS which one I should download? the zip of webtrees or source code?

**Comment by reteP-riS** [comment]
The zip file.

**Comment by abdullahaaf** [comment]
I already download the zip file and extract it on `modules_v4` directory with name `webtrees-descendants-chart`, but it still not listed on `Chart` menu or `All Modules`.

Did I miss something?

**Comment by reteP-riS** [comment]
Can you show us the contents of modules_v4 **and** the subfolder webtrees-descendants-chart, please?

**Comment by abdullahaaf** [comment]
@reteP-riS this is my `modules_v4` content
<img width="638" alt="image" src="https://github.com/magicsunday/webtrees-descendants-chart/assets/16618535/9a49a3d7-e6dc-4f69-b071-94eb9c5ebe18">

and this is my `webtrees-descendants-chart` content
<img width="566" alt="image" src="https://github.com/magicsunday/webtrees-descendants-chart/assets/16618535/3b8d4c2a-c838-4602-b66d-a4e607ed5cc6">

**Comment by reteP-riS** [comment]
Looks ok to me, but I wonder why you have the example modules installed. They are no longer part of the official webtrees releases. Did you install them manually later?
Make sure you downloaded the latest official webtrees release as zip file from https://github.com/fisharebest/webtrees/releases and not the latest code which is work in progress.
Check the access rights for modules_v4 and its subfolders.
Otherwise I'm running out of clues.

**Comment by abdullahaaf** [comment]
for external module, is it ok to install it after I'm done with initial setup ?

for example module I think it come from webtrees downloaded from official website https://webtrees.net/download

**Comment by reteP-riS** [comment]
Yes, Sir!

**Comment by abdullahaaf** [comment]
Thanks, I try to re-install webtrees from https://github.com/fisharebest/webtrees/releases and external module listed.
