### ISSUE TITLE
ruined output (for left and right orientation)

### ISSUE THREAD

**Issue by arbor95** [magicsunday/webtrees-descendants-chart#60]
**Describe the bug**
can not see anything or simply lines

**To Reproduce**
1. Go to [Heinrich Frese](https://freris.de/tree/frese/webtrees-descendants-chart/I9?generations=4&hideSpouses=0&showMarriedNames=0&openNewTabOnClick=1&layout=right)
2. Click on 'left', click on 'view'
3. See output

**Expected behavior**
see images and data, moving around

**Screenshots**
not necesssary
**Desktop (please complete the following information):**
 - Version 124.0.6367.119 (Offizieller Build) (64-Bit)
 - Webtrees version 2.1.20
 - Version of descendants chart 1.8.1

**Additional context**
None

**Comment by magicsunday** [comment]
Seems to Happen at https://freris.de/tree/frese/individual/XI8/Johann-Frese 

If you select him with 2 generations the display gets corrupted. Can you extract his gedcom part and append it here, so I can test it?

**Comment by arbor95** [comment]
Sorry for the delay.
[clippings.ged.txt](https://github.com/magicsunday/webtrees-descendants-chart/files/15231661/clippings.ged.txt)
I suppose this candidate (a second wife, without real data)
[Bernard.ged.txt](https://github.com/magicsunday/webtrees-descendants-chart/files/15231721/Bernard.ged.txt)

console debug output:
VM457:1 Uncaught TypeError: n[1] is not iterable
    at SVGTextElement.<anonymous> (<anonymous>:1:64736)
    at Te.data (<anonymous>:1:25441)
    at $i.addNameElements (<anonymous>:1:65260)
    at <anonymous>:1:64636
    at Te.call (<anonymous>:1:26941)
    at $i.appendName (<anonymous>:1:64335)
    at Ri.drawNode (<anonymous>:1:74205)
    at <anonymous>:1:72529
    at Te.call (<anonymous>:1:26941)
    at Ri.nodeEnter (<anonymous>:1:72515)


Further test give a hint:
The second wife of Bernard is N.N., handled as special case.
When renaming the surname (perhaps to DoNotKnow) the bug is gone.

**Comment by magicsunday** [comment]
The problem no longer seems to exist in the current development branch (https://github.com/magicsunday/webtrees-descendants-chart/tree/2.1). Is there a way for you to test this? Unfortunately, I won't be able to create a new release today or tomorrow.

**Comment by arbor95** [comment]
seems as if its gone there. Only thing is, the presented name is now N. instead of N.N.
![Nachkommentafel von Heinrich Frese](https://github.com/magicsunday/webtrees-descendants-chart/assets/6124739/a0e50ed6-8aff-4e14-a659-0ad1ca3a5f02)

**Comment by magicsunday** [comment]
What do the standard Webtrees charts show with this name?

**Comment by arbor95** [comment]
std webtrees shows N.N.

![image](https://github.com/magicsunday/webtrees-descendants-chart/assets/6124739/8d8e72fa-afa7-425f-84c8-f0f8727b1c25)

**Comment by magicsunday** [comment]
Should be fixed in latest version in branch 2.1
