### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Fa10175** [magicsunday/webtrees-descendants-chart#68]
In your Descendants, Fan, Pedigree modules, how do you disable SVG or PNG exports?
An option in the configuration could do this too.
this need is for me, I don't want the people who consult my site to be able to do this action. 
Thanks

**Comment by magicsunday** [comment]
Configurable in the module preferences

![grafik](https://github.com/user-attachments/assets/131a0617-8165-4bee-af48-dd988e3067ee)

**Comment by Fa10175** [comment]
i download the lastest version 2.0.0 again 
see my screen capture
![Screenshot 2024-12-22 at 13-37-20 Descendants chart](https://github.com/user-attachments/assets/df25fb9c-2583-4879-b267-88a849742c0c)
i don't have these option

**Comment by Fa10175** [comment]
if i download dev version 
i have
`Class "MagicSunday\Webtrees\ModuleBase\Module\VersionInformation" not found …\modules_v4\webtrees-descendants-chart\src\Traits\ModuleCustomTrait.php:50

#0 …\app\Http\RequestHandlers\ControlPanel.php(140): MagicSunday\Webtrees\DescendantsChart\Module->customModuleLatestVersion()
....`

**Comment by Fa10175** [comment]
Sorry i download the version 2.0.1 from DEV 2.2
and i have the option
Thanks

**Comment by Fa10175** [comment]
after validate hide svg and png inside modules
if i try i have these messages:
`Class "MagicSunday\Webtrees\ModuleBase\Processor\NameProcessor" not found …\modules_v4\webtrees-fan-chart\src\Facade\DataFacade.php:141`
`Class "MagicSunday\Webtrees\ModuleBase\Processor\NameProcessor" not found …\modules_v4\webtrees-descendants-chart\src\Facade\DataFacade.php:297`
`Class "MagicSunday\Webtrees\ModuleBase\Processor\NameProcessor" not found …\modules_v4\webtrees-pedigree-chart\src\Facade\DataFacade.php:158`
