### ISSUE TITLE
PNG Export does not seem to work

### ISSUE THREAD

**Issue by snowborn** [magicsunday/webtrees-descendants-chart#70]
**Describe the bug**

**To Reproduce**
1. Go to 'the plugin page'
2. Click on 'select a person to create the tree for'
3. Click on "export PNG"
4. the exported file is not a png that any of my image programs recognize

**Expected behavior**
The PNG can be opened and correctly interpreted by any image program

**Screenshots**
See attacked file which is an example export.

**Desktop (please complete the following information):**
 - Browser Firefox
 - Webtrees version 2.2.1
 - Version of descendants chart 2.0
![descendants-chart_failed](https://github.com/user-attachments/assets/a498b198-b640-47af-9405-2f84525f0abe)

**Comment by magicsunday** [comment]
Hi,

Hi, I can't reproduce your error. For me, a valid PNG is created that I can view outside of the browser.

Does the problem occur for all people in your tree?
Does the problem also occur in my Pedigree Chart or Fan Chart module?
Does the problem also occur in a completely new tree?
Is an error message displayed somewhere (web console, error log, ...)?
What operating system are you using?
Does the problem also occur under Webtrees 2.1 and the corresponding module version?

**Comment by snowborn** [comment]
Ok, I tried a different Firefox derivate and got it to work now.

Before I was using it with LibreWolf and the console showed the error:
Blocked ...index.php?route=%2Ftree%2Ftree1%2Fwebtrees-pedigree-chart%2FX1&generations=4&showEmptyBoxes=0&layout=right&openNewTabOnClick=1&showAlternativeName=0 from extracting canvas data because no user input was detected.

It happened with at least 3 people in my tree.
It also happened with a completely new tree.
I do not see anything in the servers logs 
I do get a 302 status message in the logs. (redirect?)
