### ISSUE TITLE
spouses

### ISSUE THREAD

**Issue by arbor95** [magicsunday/webtrees-descendants-chart#8]
I am missing the possibilty to show the spouses.

**Comment by AlexKalopsia** [comment]
Agreed. I love this module, but not being able to visualize entire families is actually very limiting. Hope this gets enhanced eventually!

**Comment by wp4711** [comment]
Add spouse would be a nice feature! Is it planned to add that feature?

**Comment by enes73** [comment]
Also, if someone have 2 or more wifes, children should be sorted by man/wife pair. You also can add marriage date (if exist).

Thanks for GREAT graph module.

**Comment by leonardo091800** [comment]
yes, would love to see spouses as well!!
thanks for the great plugin

**Comment by photon-flip** [comment]
This would be my most used chart if it had spouses. Please, please please.

**Comment by magicsunday** [comment]
It took a long time, but I think it's mostly okay now. Please give it a try:

![grafik](https://user-images.githubusercontent.com/564393/221640225-22f413c9-e0dc-4f8c-a8e0-e5e2d99e258d.png)

With composer:

Webtrees v2.1
    `composer require magicsunday/webtrees-descendants-chart:2.1.x-dev --update-no-dev`

Webtrees v2.2
    `composer require magicsunday/webtrees-descendants-chart:dev-main --update-no-dev`
