### ISSUE TITLE
Number of possible generations

### ISSUE THREAD

**Issue by mpwt** [magicsunday/webtrees-descendants-chart#9]
Könnte die max. Generationsanzahl reduziert werden? Die aktuell wählbaren 25 Generationen lassen die Internetseite "einfrieren". Eine maximale Anzahl von 10-15 sollte an sich ausreichen, zumal die Lesbarkeit da schon stark abgenommen hat.

**Comment by magicsunday** [comment]
Siehe mein Kommentar in https://github.com/magicsunday/webtrees-pedigree-chart/issues/24
